import $$ from '../TestHelpers';

$$.suite('Replicate issue', () => {
  $$.test(`#133 - just installed, and TypeError: this._items[key].slice`, () => {
    const expectedOutput = {
      '!': ' XML Sitemap generated by Dimas Lanjaka ',
      '?': 'xml-stylesheet type="text/xsl" href="sitemap.xsl"',
      sitemapindex: {
        '@xmlns': 'http://www.sitemaps.org/schemas/sitemap/0.9'
      }
    }
    const xml = `
    <?xml version="1.0" encoding="UTF-8"?><?xml-stylesheet type="text/xsl" href="sitemap.xsl"?>
    <sitemapindex xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">
    </sitemapindex>
    <!-- XML Sitemap generated by Dimas Lanjaka -->
    `;
    const obj = $$.create(xml).end({ format: 'object' });
    $$.deepEqual(obj, expectedOutput)
  });
});
